[package]
name = "chalbik"
version = "0.1.0"
edition = "2021"
authors = ["Dan Denkijin <denkijin@proton.me>"]
repository = "https://github.com/dandenkijin/chalbik"

[dependencies]
ratatui = "0.29.0"
tui-rain = "1.0.1"
crossterm = "0.28.1"
color-eyre = "0.6.2"
rand = "0.8.5"